import { InstituteRecord } from './types';

export const INSTITUTE_COURSES = [
  'Full Stack Development Course',
  'Data Science Course',
  'Digital Marketing Course',
  'Python Programming & AI',
  'Web Design & Development',
  'Graphic Designing & Video Editing',
  'Java Full Stack Development',
  'Cyber Security & Ethical Hacking',
  'UI / UX Design',
];

export const INSTITUTE_SOURCES = [
  'Google Search / Website',
  'Instagram',
  'Facebook / Meta Ads',
  'JustDial',
  'Direct Walk-in (Center)',
  'Referral / Friend',
  'Poster / Banner / Pamphlet',
  'WhatsApp Enquiry',
  'Other',
];

export const INSTITUTE_STATUSES = [
  'New Lead',
  'Active On Call',
  'Center Visit',
  'Demo / Counseling',
  'Follow-Up',
  'Batch Processing',
  'Hold',
  'Lost',
  'Admission',
];

export const DEFAULT_INSTITUTE_RECORDS: InstituteRecord[] = [
  {
    id: 'inst-1',
    firstName: 'Mohd Adil',
    lastName: 'Ansari',
    parentName: 'Farooq Ansari',
    mobile: '9820112233',
    alternateMobile: '9820112234',
    parentEmail: 'ansari.farooq@example.com',
    gender: 'Male',
    course: 'Full Stack Development Course',
    qualification: 'B.Sc Computer Science',
    institutionName: 'Bhavans College',
    city: 'Mumbai',
    enquiredFrom: 'Instagram',
    status: 'New Lead',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-2',
    firstName: 'Sara',
    lastName: 'Fatima',
    parentName: 'Sheikh Tariq',
    mobile: '9876543210',
    parentEmail: 'sara.fatima@example.com',
    gender: 'Female',
    course: 'Data Science Course',
    qualification: 'BCA',
    institutionName: 'Rizvi College',
    city: 'Mumbai',
    enquiredFrom: 'Google Search / Website',
    status: 'Demo / Counseling',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-3',
    firstName: 'Zaid',
    lastName: 'Khan',
    parentName: 'Tariq Khan',
    mobile: '9123456780',
    gender: 'Male',
    course: 'Cyber Security & Ethical Hacking',
    qualification: '12th Science',
    institutionName: 'St. Xavier Junior College',
    city: 'Thane',
    enquiredFrom: 'Referral / Friend',
    status: 'Admission',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'inst-4',
    firstName: 'Alok',
    lastName: 'Verma',
    parentName: 'Ramesh Verma',
    mobile: '9988776655',
    gender: 'Male',
    course: 'Digital Marketing Course',
    qualification: 'B.Com',
    institutionName: 'National College',
    city: 'Navi Mumbai',
    enquiredFrom: 'WhatsApp Enquiry',
    status: 'Follow-Up',
    createdAt: new Date().toISOString(),
  },
];
